### ISSUE TITLE
altIdentifier DOI form

### ISSUE THREAD

**Issue by BaptisteCecconi** [ivoa-std/VOResource#9]
The current version of the text is stating to use the `doi:10.NNNN/abcd` form instead of the full https URI. However, the [DataCite](https://support.datacite.org/docs/datacite-doi-display-guidelines) and [CrossRef](https://www.crossref.org/display-guidelines/) display guidelines are both clearly stating that the https URI form should be used as much possible. 

So, according to [the paragraph at lines 540-543](https://github.com/ivoa-std/VOResource/blob/3503dfa1dcc3f4ef96d502e6b105fdc3b9ebad61/VOResource.tex#L540C1-L543C40), we should update the text and recommend the use of the `https://doi.org/...` form. 

I can propose a PR, if we want.

**Comment by msdemlei** [comment]
On Mon, May 20, 2024 at 05:04:45PM -0700, Baptiste Cecconi wrote:
> The current version of the text is stating to use the `doi:10.NNNN/abcd` form instead of the full https URI. However, the [DataCite](https://support.datacite.org/docs/datacite-doi-display-guidelines) and [CrossRef](https://www.crossref.org/display-guidelines/) display guidelines are both clearly stating that the https URI form should be used as much possible.
>
> So, according to [the paragraph at lines 540-543](https://github.com/ivoa-std/VOResource/blob/3503dfa1dcc3f4ef96d502e6b105fdc3b9ebad61/VOResource.tex#L540C1-L543C40), we should update the text and recommend the use of the `https://doi.org/...` form.

No, let's not do it.  Whatever reasons Datacite and Crossref have for
their recommendation, I argue that for RegTAP it is much more
important to have clear and simple rules on how to figure out the
type of an identifier (and "it's always doi:" is a lot better than
"startswith https://doi.org, but it could be doi:, too, and
historically, http://dx.doi.org is conceivable, too").  What clients
do to present these DOIs is then up to them, and it's trivial for
them to return "https://doi.org/"+alt_identifier[4:].

I mention in passing that I think baked-in resolver URLs isn't a
great recommendation anyway; in effect, they suggest there is and can
only be one DOI resolver, and that's something I'm deeply skeptical
about as a matter of principle.

So... can we close as WONTFIX?

**Comment by BaptisteCecconi** [comment]
Well then, there should be an update of the text. The reason of using the `doi:` prefix is internal, not related to external recommendation. The same should be applied to orcid, then I guess, if we want to be consistent.

We should also add a paragraph on how to resolve each prefix to http URI.

**Comment by msdemlei** [comment]
Well, I haven't done anything on this bug and would like to do for PR.  Can I close this bug?  Or do you have something like minimal requirements for closing it?
